SELECT * FROM Employees;
SELECT * FROM projects;

-- LETS FIND EMPLOYEES FROM THE ENGINEERING DEPARTMENT WHO ARE WORKING ON ANY PROJECT

SELECT * FROM Employees O
WHERE Department = 'ENGINEERING' AND EXISTS(
	SELECT * FROM PROJECTS I
	WHERE O.employee_id = I.employee_id);

SELECT * FROM Employees O
WHERE Department = 'ENGINEERING' AND NOT EXISTS(
	SELECT * FROM PROJECTS I
	WHERE O.employee_id = I.employee_id);